default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  timeout: 5000
  reconnect: true
  username: vagrant
  password:

development:
  <<: *default
  database: check_in_app_development

test:
  <<: *default
  database: check_in_app_test

production:
  <<: *default
  database: db/production.sqlite3
