default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: clock_in_app
  password: 

development:
  <<: *default
  database: check_in_app_development

test:
  <<: *default
  database: check_in_app_test

production:
  <<: *default
  database: check_in_app_production
